#
# ADD THIS CONTENT TO DOCKER-COMPOSE file.
#

version: "3.7"
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./conf/basic-nginx/nginx.conf:/etc/nginx/user.conf.d:ro
      - ./conf/basic-nginx/passwords:/etc/nginx/passwords:ro
      - ./conf/basic-nginx/certs:/certs:ro
      - ./conf/basic-nginx/logs:/etc/nginx/logs
      - ./conf/basic-nginx/html:/etc/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
