#
# ADD THIS CONTENT TO DOCKER-COMPOSE file.
#
# Choose an image from https://hub.docker.com/_/nginx
# Try to use the alpine image more stable, but not the latest!

version: "3.7"
services:
  nginx:
    container_name: nginx
    image: nginx:1.19.4-alpine
    restart: unless-stopped
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - ./conf/basic-nginx/conf.d:/etc/nginx/conf.d
      - ./conf/basic-nginx/passwords:/etc/nginx/passwords:ro
      - ./conf/basic-nginx/certs:/certs:ro
      - ./conf/basic-nginx/logs:/etc/nginx/logs:rw
      - ./conf/basic-nginx/html:/etc/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
