#
# ADD THIS CONTENT TO DOCKER-COMPOSE file.
#
# Configure absolute domain and info.
# Try not to left this in production!!

version: "3.7"
services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_ABSOLUTE_URI: https://your-domain.com/phpmyadmin/
      PMA_ARBITRARY: 1
    volumes:
      - "./conf/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php:ro"
      - /sessions
    networks:
      - app-network
    depends_on:
      - mysql

networks:
  app-network:
    driver: bridge
