#
#  ADD THIS CONTENT TO DOCKER-COMPOSE.YML
#
#  Usage:
#  Erase "ports: 27017:27017" to make mongo not accesible from outside the compose.
#  Add to .env file the MONGO_INITDB_ROOT_USERNAME and MONGO_INITDB_ROOT_PASSWORD variables.
#  You can change the mongo configuration in the file /conf/mongo/mongod.conf.
#  Docs: https://docs.mongodb.com/manual/reference/configuration-options/

version: "3.7"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_USERNAME: ${MONGO_USERNAME}
      MONGO_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
      - ./conf/mongo/logs:/root/logs:rw
      - "./conf/mongo/init.sh:/docker-entrypoint-initdb.d/init.sh"
    networks:
      - app-network

volumes:
  mongo_data:
  mongo_config:

networks:
  app-network:
    driver: bridge
