#
# ADD THIS CONTENT TO DOCKER-COMPOSE file.
#
# Usage: Update the .env file with the specified variables for MYSQL (MYSQL_ROOW_PASSWORD, MYSQL_DATABASE, MYSQL_USER, MYSQL_PASSWORD).
# MYSQL with docker-compose it's a bit tricky. Maybe you will need to rerun the docker container after starting it the first time.

version: "3.7"
services:
  mysql:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      #      - "./conf/mysql/conf.d:/etc/mysql/conf.d:ro"
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
