#
#  ADD THIS CONTENT TO DOCKER-COMPOSE.YML
#
#  Usage:
#  Do not expose any port (it's easier to configure security with nginx as a reverse proxy than in wordpress itself).
#  Edit the environment variables to use MYSQL/MariaDB with Wordpress (in DB_HOST you should have a mysql container).
#  Try to have a database user different to other apps users (if someone steals information, will have only your wordpress credentials).
#
#  Edit the environment variable WORDPRESS_LOCATION. It's the subdirectory where you will put wordpress. Vg: domain.com/this_url or domain.com/this_other_url
#  The wordpress location should be "/this_url" or "/this_other_url". If you wont' have a subdir, just use "/".
#  You can install different themes and plugins in the dirs conf/wordpress/themes and /plugins.
#
#  You can also configure
#  You can configure wordpress with the WORDPRESS_CONFIG_EXTRA environment variable. Please set the WP_HOME and WP_SITEURL urls.
#  These variables will be inserted to wp-config.php.
#  You can see how to configure wordpress here: https://www.wpbeginner.com/beginners-guide/how-to-edit-wp-config-php-file-in-wordpress/#:~:text=Simply%20right%20click%20on%20the,like%20Notepad%20or%20Text%20Edit.
#  If we are behind a proxy with SSL; we also must set that in wp-config: https://wordpress.org/support/article/administration-over-ssl/#using-a-reverse-proxy
#
#  Wordpress original image can't send emails, so this is a modified version to allow sendmail function.
#  Docs on how to send mails with wordpress: https://github.com/docker-library/wordpress/issues/30#issuecomment-317511836

version: "3.7"
services:
  wordpress:
    container_name: wordpress
    build:
      context: ./dockerfiles/wordpress
      dockerfile: dockerfile
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql_wordpress:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME','https://your-domain.com${WORDPRESS_LOCATION}');
        define('WP_SITEURL','https://your-domain.com${WORDPRESS_LOCATION}');          
        define('SCRIPT_DEBUG', true );
        define('WP_DEBUG_LOG', true );
        define('WP_DEBUG_DISPLAY', true );
        define('FORCE_SSL_ADMIN', true);
        define('FS_METHOD','direct');
        define( 'DISALLOW_FILE_EDIT', true );
        $$_SERVER['HTTPS'] = '1';
        if (isset($$_SERVER['HTTP_X_FORWARDED_HOST'])) {
          $$_SERVER['HTTP_HOST'] = $$_SERVER['HTTP_X_FORWARDED_HOST'];
        }
    volumes:
      - wordpress:/var/www/html${WORDPRESS_LOCATION}
      - ./conf/wordpress/themes:/var/www/html${WORDPRESS_LOCATION}/wp-content/themes/:rw
      - ./conf/wordpress/plugins:/var/www/html${WORDPRESS_LOCATION}/wp-content/plugins/:rw
    working_dir: /var/www/html${WORDPRESS_LOCATION}
    networks:
      - app-network
    depends_on:
      - mysql_wordpress

volumes:
  wordpress:

networks:
  app-network:
    driver: bridge
