#
# ADD THIS CONTENT TO DOCKER-COMPOSE file.
#
# Do not exopse any port.

version: "3.7"
services:
  adminer:
    image: adminer:latest
    restart: always
    environment:
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: "tables-filter tinymce"

networks:
  app-network:
    driver: bridge
