#
# ADD THIS CONTENT TO DOCKER-COMPOSE file.
#
# Do not exopse any port.
# The file is modifed to disable root login.

version: "3.7"
services:
  adminer:
    container_name: adminer
    build:
      context: ./dockerfiles/adminer
      dockerfile: dockerfile
    restart: always
    environment:
      ADMINER_DESIGN: nette
      ADMINER_PLUGINS: "tables-filter"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
